---
# tasks file for aws-launch-instance
- name: start a instance with public ip address 
  amazon.aws.ec2_instance: 
    name: "{{ ec2_name }}"
    instance_type: "{{ ec2_type }}"
    security_group: "{{ sg_name }}"
    #key_name: generic_key_pair
    region: "{{ region_name }}"
    aws_access_key: "{{ ec2_access_key }}" 
    aws_secret_key: "{{ ec2_secret_key }}"
    network: 
      assign_public_ip: True 
    image_id: "{{ image_name }}"
    tags:
      Environment: testing 

- name: Create key pair and save
  amazon.aws.ec2_key: 
    name: "{{ ec2_key_name }}"
    region: "{{ region_name }}"
    aws_access_key: "{{ ec2_access_key }}" 
    aws_secret_key: "{{ ec2_secret_key }}"
  register: ec2_generate_key
  
- name: Save keypair 
  copy: content="{{ ec2_generate_key.key.private_key }}" dest="./aws_instance_key.pem" mode=0600 
  when: ec2_generate_key.changed 

 

