---
# tasks file for win-java-env-setup
- name: Load java env playbook 
  ansible.builtin.include_tasks: javaEnvpathSetup.yml

- name: set status
  ansible.builtin.set_fact: 
    javaEnvPathStatus: "FAIL"
  when: envJavapathCount|int > 0

- name: set status
  ansible.builtin.set_fact: 
    javaEnvPathStatus: "PASS"
  when: envJavapathCount|int == 0

- name: Print success message 
  ansible.builtin.set_fact: 
    messageInfo: "{{ messageInfo + ['Java env path Successfully set']}}"
  when: javaEnvPathStatus == "PASS"

- name: Print Failure message 
  ansible.builtin.set_fact: 
    messageInfo: "{{ messageInfo + ['Java env path Failed to set']}}"
  when: javaEnvPathStatus == "FAIL"


  